### ISSUE TITLE
Develop + Run tests + Release vith gems

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#104]
Write short cheat-sheet on how to work with gems through the release cycle process.
Use 'rmv gemset' well. Each release should have it's own gemset?
How do we name/number each release?

**Comment by AlexeyNemytov** [comment]
How is it going on?

**Comment by kolmanv** [comment]
Added the release process in wiki page.
Development + testing done.
Opened new issue for releasing 'round_clock_testing' branch.
