### ISSUE TITLE
Documentation for the first release

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#108]
1. Specification Document
2. Release Description
3. Test report

**Comment by vshiray** [comment]
Did you get a feedback about the documentation from Yaron, Gena or Kolman ?

**Comment by AlexeyNemytov** [comment]
yes will update accordingly

**Comment by kolmanv** [comment]
Depends on: Documentation for file copy protocol, issue #115

**Comment by kolmanv** [comment]
Blocked by other issues, unassigning due to non-activity..

**Comment by kolmanv** [comment]
Closing as duplicate with other issues.
