### ISSUE TITLE
Gem dependancies of sub-gems

### ISSUE THREAD

**Issue by genadyp** [bbfsdev/bbfs#111]
According to release notes:
The release should depend on specific gem versions. We should validate that sub-gems will use same gems as content_server uses.

**Comment by genadyp** [comment]
Three gems:
- master depends on sub1 and sub2.
- sub1 depends on sub2

Following experiments were done:
1. master gem depends on sub1(0.0.1), sub2(0.0.1). sub1 depends on sub2(0.0.2).
   Order of requirements in master:
   require 'bbfs_sub1'
   require 'bbfs_sub2'
   Output:
   
   > /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:774:in `block in activate_dependencies': can't satisfy 'bbfs_sub2 (= 0.0.1)', already activated 'bbfs_sub2-0.0.2' (Gem::LoadError)
2. Same as 1. but with different order of requirements in master:
   require 'bbfs_sub2'
   require 'bbfs_sub1'
   Output:
   
   > /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:774:in `block in activate_dependencies': can't satisfy 'bbfs_sub2 (= 0.0.1)', already activated 'bbfs_sub2-0.0.2' (Gem::LoadError)
3. Same as 2. but code from sub2 was used before code from sub1.
   Output:
   >/usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:774:in `block in activate_dependencies': can't satisfy 'bbfs_sub2 (= 0.0.1)', already activated 'bbfs_sub2-0.0.2' (Gem::LoadError)
4. Same as 3. but master depends on sub1(no hard version), sub2(0.0.1). sub1 depends on sub2(no hard version)
   Output:

```
MASTER: 0.0.2
      SUB2: 0.0.1
      SUB1: 0.0.2
          SUB2: 0.0.1
```

<p>Installed gems:
bbfs_master (0.0.2, 0.0.1)
bbfs_sub1 (0.0.2, 0.0.1)
bbfs_sub2 (0.0.2, 0.0.1)
5. master depends on sub1(no hard version), sub2(0.0.1). sub1 depends on sub2(no hard version)
Order of requirements in master:
require 'bbfs_sub1'
require 'bbfs_sub2'
sub1 code used before sub2 code (but in sub1 the first action is a requirement for sub2)

```
MASTER: 0.0.2
      SUB1: 0.0.2
         SUB2: 0.0.1
      SUB2: 0.0.1
```

<p>Installed gems:
bbfs_master (0.0.2, 0.0.1)
bbfs_sub1 (0.0.2, 0.0.1)
bbfs_sub2 (0.0.2, 0.0.1)

Experiment code available on: f1:/tmp/genadyp/subgems_test

**Comment by genadyp** [comment]
@kolmanv , verify it, please.
May be @vshiray also need to verify it?
Could we, in general, ask @vshiray  for review?
@yarondbb , looks that we can continue with gems as planned.

**Comment by AlexeyNemytov** [comment]
@genadyp thanks

**Comment by kolmanv** [comment]
Great, closing issue.
