### ISSUE TITLE
Write documentation for file copy protocols

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#115]

**Comment by kolmanv** [comment]
@kolmanv
@genadyp 
Please talk to Kolman for details.

**Comment by kolmanv** [comment]
Gena, what is the status?

**Comment by kolmanv** [comment]
Maybe anassign?

**Comment by genadyp** [comment]
I have a time to work only on Fridays. Get the mission last Friday will continue this Friday.

**Comment by genadyp** [comment]
Status: Learning protocols

**Comment by kolmanv** [comment]
@yarondbb Is this issue may be closed?

**Comment by kolmanv** [comment]
@genadyp  Is this issue may be closed?

**Comment by genadyp** [comment]
@kolmanv 
Kolman, review, please
[FileCopy Protocols](https://docs.google.com/document/d/1KFQLjLezrnveU2d9BG5LwYEEwcj-Vr8h71c14qiDxVc/edit#)

**Comment by bbfsdev** [comment]
Great work. Will go over this.

**Comment by bbfsdev** [comment]
Please resolve the comments in the documentation and pass the file to Alexey to add it to wiki.

**Comment by genadyp** [comment]
Comments were resolved
