### ISSUE TITLE
Give Yaron permissions to publish gems

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#117]
Blockin #114 (release first version).

**Comment by kolmanv** [comment]
I gave permissions to bbfsdev to the following gems:
file_monitoring
content_data
content_server
file_copy
file_indexing
params
log
networking
run_in_background

via the following command:
gem owner run_in_background --add bbfsdev@gmail.com

file_utils - don't belong to us. What should we do with it?
validations - Gena please add bbfsdev@

Yaron when you release, please do this via bbfsdev@ username.

**Comment by kolmanv** [comment]
Yaron please sing in for https://rubygems.org

**Comment by genadyp** [comment]
user bbfsdev was added as validations gem collaborator

Owners for gem: validations
- bbfsdev@gmail.com
- nukegluk@gmail.com

**Comment by genadyp** [comment]
Yaron (@yarondbb), do you have permissions for all gems?

**Comment by genadyp** [comment]
Regarding file_utils.
It looks that meanwhile we don't have any gem depends on file_utils:

```
 bbfs]$ find . -name "*gemspec" -exec grep -H 'file_utils' {} \;
./file_utils.gemspec:require File.expand_path('../lib/file_utils/version', __FILE__)
./file_utils.gemspec:  s.name        = 'file_utils'
./file_utils.gemspec:  s.files       = Dir['lib/file_utils.rb', 'lib/file_utils/**/*'] \
./file_utils.gemspec:  s.test_files  = Dir['spec/file_utils/**/*', 'test/file_utils/**/*'] \
./file_utils.gemspec:  s.executables = ['file_utils']
```

So it doesn't block the release.

**Comment by kolmanv** [comment]
So it is not part of the release.
We can switch to other name for the gem.

**Comment by kolmanv** [comment]
Closing the issue, Yaron you are good to go with the release.
