### ISSUE TITLE
Write documentation for log gem

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#118]

**Comment by kolmanv** [comment]
Blocking #108

**Comment by kolmanv** [comment]
@yarondbb

**Comment by kolmanv** [comment]
Please add link to examples (latest). Update example.

**Comment by kolmanv** [comment]
@yarondbb 
Yaron, what is the status? Maybe unassign?

**Comment by kolmanv** [comment]
@yarondbb Is this issue may be closed?

**Comment by yarondbb** [comment]
I am working on it. Will coplete soon (Probalby Monday)

**Comment by bbfsdev** [comment]
Any news?

**Comment by yarondbb** [comment]
@AlexeyNemytov , I sent you the file via email (could not attach it here since .doc type is not supported)

**Comment by bbfsdev** [comment]
If I understand correctly, Alexey have the file, he needs to add it to googledocs + link it to documentation page?

If that is the case, then I'm moving assignment to Alexey.

Alexey, please close this issue when the documentation is done.

@AlexeyNemytov 
@yarondbb

**Comment by bbfsdev** [comment]
Done.
