### ISSUE TITLE
Create release notes + check example files are ok.

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#125]
@yarondbb @AlexeyNemytov 

Update examples files to be synced with the release.
Write release notes:
1) How to install.
2) How to run.

blocked by #114.

Alexey, please help Yaron if he has trouble with this. If you want to may take responsibility for this task.

After this task is done, we send email to @vshiray to finalize the release.

**Comment by yarondbb** [comment]
Do we have documentation to explain backup server files structure? (bacup.data, backup romte dir, tmp dir, backup files destination(which is the monitoring path in our convention) ?

**Comment by yarondbb** [comment]
@AlexeyNemytov , Do we have documentation to explain backup server files structure? (bacup.data, backup romte dir, tmp dir, backup files destination(which is the monitoring path in our convention) ?

**Comment by AlexeyNemytov** [comment]
backup server generally explained in 1.1 System Spec
https://github.com/bbfsdev/bbfs/wiki/Documentation
you may add there

**Comment by AlexeyNemytov** [comment]
need to be updated example of testing_server.yml https://github.com/bbfsdev/bbfs/blob/master/examples/testing_server.yml 

also need basic instructions how to use testing server

**Comment by yarondbb** [comment]
@genadyp , @kolmanv , @AlexeyNemytov  Pls review release notes:

## BBFS version 1.1.0 Release notes

## Backup system, general workflow:
1. Content server monitors a set of local directories.
   1.a  The files in those  directories are indexed (calculating their SHA1).
   1.b  The indexed content is stored in a file (server content data).
   1.c  When asked content data is sent to backup server
   1.d  When asked, speific files are sent to bckup server for backup.
2. Backup server requests new/changed contents(files) from the Content server.
   2.a  Backup files (copied from content server) are stored in a destination dir
    which is also monitored, indexed and stored in a file(backup content data)
   2.b  The destination dir structure is:
        backup/destination/tmp - used to temporary files while copying from content server.
        backup/destination/remote/ - indexed data received from servers.
        backup/destination/\* - rest of dirs used to stored backup files.
   2.c Each period of time (configurable), sends request to content server to get its latest content data
   2.e Each period of time (configurable),performes a sync check between content server and itself.
   2.f If needed, requests and copy required files from content server to backup (store in destination dir)

## Install and execute from scratch

There are two application for BBFS system:
1. backup_server is an application which runs on a machine where files are stored for backup.
2. content_server is application which runs on a machine from where files are copied.
Note:  backup_server and content_server can both run on same machine.

## Installing content_server and backup_server applications from scratch:

Installing Ruby:
  Check if Ruby and rubygems are already installed by typing:'ruby -v' and "gem -v"
  If not then:
    On Windows:
      go to http://rubyinstaller.org/ - download and install Ruby.
      go to ruby site and download devkit, follow instructions to install.
    On Linux type:'sudo apt-get install ruby1.9.3'

Installing application gems:
   Type:'gem install content_server'. This can tke a while till all gems are installed.

## Executing content_server application
1. preparing content server configuration file
   Create a file with the following text(example only):
   ############# START OF FILE #################
   # Content server parameters
   local_files_port: 4444 # TCP/IP port to start server to send files to backup.
   local_content_data_port: 3333 # TCP/IP port to start server to send content data upon request from client.

# content data file, i.e., state of content server.

local_content_data_path: '~/.bbfs/var/content.data' # File to store content data

# Logging options

log_write_to_file: true  # Will print all log messages to file
log_file_path: ~/.bbfs/log/content_server.log4r
log_write_to_console: true # Will print all log messages to standard output. Default is false.
log_write_to_email: true # Will print errors to mail on system crush only . Default is false.
log_debug_level: 0 # Verbosity of logging. 0 will log only INFO messages. 3 will print ALL debug messages as well.
from_email: 'put your email address here..'
from_email_password: 'put your email password here..'
to_email: 'put your email address here..'
default_monitoring_log_path: '~/.bbfs/log/content_file_monitoring.log' # Log of file changes

# Paths to monitor\backup files from. All path files and recursive sub paths are used.

monitoring_paths:
- path: 'path_1_to_monitor' # Directory to monitor.
  scan_period: 1 # Number of seconds before initiating another directory scan.
  stable_state: 5 # Number of scan times for a file to be unchanged before his state becomes stable.
- path: 'path_2_to_monitor' # Directory to monitor.
  scan_period: 1 # Number of seconds before initiating another directory scan.
  stable_state: 5 # Number of scan times for a file to be unchanged before his state becomes stable.
  #   ... (more paths if needed)

print_params_to_stdout: true  # This will print all configuration params to console at the beginning of execution log.
############# END OF FILE #################
2. Run content server:
     content_server --conf_file=path_to_configuration_file

## Executing backup_server application
1. preparing content server configuration file
   Create a file with the following text(example only):
   ############# START OF FILE #################
   # Backup server parameters
   content_server_hostname: 'localhost'  # Default is nil
   content_server_files_port: 4444 # TCP/IP port to start server to send files to backup.
   content_server_data_port: 3333 # TCP/IP port to start server to send content data upon request from client.

# backup data file, i.e. state(index) of backup server destination folder.

local_content_data_path: '~/.bbfs/var/backup.data' # File to store content data

# Logging options

log_write_to_file: true  # Will print all log messages to file
log_file_path: ~/.bbfs/log/backup_server.log4r
log_write_to_console: true # Will print all log messages to standard output. Default is false.
log_write_to_email: true # Will print errors to mail on system crush only . Default is false.
log_debug_level: 0 # Verbosity of logging. 0 will log only INFO messages. 3 will print ALL debug messages as well.
from_email: 'put your email address here..'
from_email_password: 'put your email password here..'
to_email: 'put your email address here..'
default_monitoring_log_path: '~/.bbfs/log/backup_file_monitoring.log' # Log of file changes

# Paths to monitor\backup files from. All path files and recursive sub paths are used.

monitoring_paths:
- path: 'path_to_destination_backup_folder' # Destination path to store copied backup files and to monitor.
  scan_period: 1 # Number of seconds before initiating another directory scan.
  stable_state: 5 # Number of scan times for a file to be unchanged before his state becomes stable.

# cycles of fetch period used by backup server to ping content server for its content

remote_content_save_timeout: 120

# Cycles where backup is chcking if sync is required between remote and backup contents

backup_check_delay: 60

print_params_to_stdout: true  # This will print all configuration params to console at the beginning of execution log.
############# END OF FILE #################
1. Run backup server:
    backup_server --conf_file=path_to_configuration_file

## Uninstalling all gems

Unix - type:
  for x in `gem list --no-versions`; do gem uninstall $x -a -x -I; done
Windows - type:
  ruby -e "`gem list`.split(/$/).each { |line| puts `gem uninstall -Iax #{line.split(' ')[0]}` unless line.empty? }"
Note: Be aware to use it when some other programs run on ruby and use different gems.
If this is a situation remove gems manually and don’t remove ruby.

## Uninstalling ruby (will also uninstall all gems)
1. In windows - uninstall Ruby (from ruby193/unins000.exe) and delete ruby193 folder.
2. In linux - sudo apt-get purge ruby_. If this not help use: sudo apt-get autoremove ruby_
   Note: Be aware to use it when some other programs run on ruby and use different gems.
   If this is a situation remove gems manually and don’t remove ruby.

## Validation:

Performed on 2 linux machines during a week.
During validation, files were generated randomly on content server machine.
@kolmanv pls add size of files which were backuped up..
Each 6 hours, backup server files compared against the expected files.

## Documentation:

Can be found at: https://github.com/bbfsdev/bbfs/wiki/Documentation

**Comment by kolmanv** [comment]
I have copied the document to googledocs, please comment/edit there.
[link to document](https://docs.google.com/document/d/1qFMYTv-iZFA1sZOBLxBjCbSPIHwtCuITl_8u_QW936I/edit)

**Comment by kolmanv** [comment]
Reviewing the document...

**Comment by kolmanv** [comment]
Document is ready. Please go ahead with the release.

**Comment by kolmanv** [comment]
@yarondbb Is this issue may be closed?

**Comment by kolmanv** [comment]
@yarondbb Is this issue may be closed?

**Comment by yarondbb** [comment]
yes
