### ISSUE TITLE
Could not run content_server 1.0.0

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#126]
@yarondbb  @kolmanv 
Looks like some basic commands to run the system were changed
I ran --help and could not find --remote_server
I found --content_server_hostname //String, default:
        IP or DNS of backup server.

Could not find  user name and password commands?

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
content_server --remote_server=f2.test.kbb1.com --backup_username=alexeyn --backup_password=kavana2012 --content_data_path=/home/alexeyn/.bbfs/var/server_content.data --monitoring_config_path =/home/alexeyn/.bbfs/etc/file_monitoring.yml
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/params-1.0.0/lib/params.rb:378:in `block in parse_command_line_arguments': invalid option: --remote_server=f2.test.kbb1.com (OptionParser::InvalidOption)
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/params-1.0.0/lib/params.rb:312:in`new'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/params-1.0.0/lib/params.rb:312:in `parse_command_line_arguments'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/params-1.0.0/lib/params.rb:253:in`init'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/gems/content_server-1.0.0/bin/content_server:12:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/bin/content_server:19:in`load'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/bin/content_server:19:in `<main>'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in`eval'
        from /usr/local/rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in `<main>'

**Comment by yarondbb** [comment]
Flags have changed
Pls see examples:
  https://github.com/bbfsdev/bbfs/blob/master/examples/config_backup_server.yml
  https://github.com/bbfsdev/bbfs/blob/master/examples/config_content_server.yml
Also, for backup server, I put this parameter value:
  backup_check_delay: 120 #this works for me fine!
(this parameter controlls the seconds to wait to ask the server for new contents. the default it 5 seconds which makes the system go creazy.. @kolmanv what is the value you used for round clock testings?)

**Comment by AlexeyNemytov** [comment]
@yarondbb 
Thanks Friend! 
It runs Ok locally. 
I need to send files to f2  wich is protected by password and username
What values to be used to define it

**Comment by kolmanv** [comment]
@genadyp @vshiray 
Great work guys! The issue dynamics works.
