### ISSUE TITLE
Unable to run Rake file for version

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#127]
No rake file exist for the release content_server 1.0.0
@kolmanv  @yarondbb

**Comment by yarondbb** [comment]
Do we need speciall rake file for the release @kolmanv ?
You can type: 
  gem install content_server
this installs ALL required gems to execute content server. Both BBFS gems and infrastructure gems such as Algorithms and net.

**Comment by kolmanv** [comment]
rake file is not needed for the release (for the user). It is needed for our development and release process. But the users don't ever use it.

**Comment by kolmanv** [comment]
This is a cleanup issues after we release.

**Comment by AlexeyNemytov** [comment]
ok

**Comment by kolmanv** [comment]
I suggest leaving this as open bug, to add rake as needed.
