### ISSUE TITLE
Run 24/7 test for master

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#129]
Mark git repository and at that point run 24/7 test for one week to validate new content data is good.

**Comment by kolmanv** [comment]
@AlexeyNemytov please consider if you have time to do those two tasks within the next week.
You can do this issue with task #130, as they are related.

**Comment by AlexeyNemytov** [comment]
@kolmanv 
Will take it

**Comment by AlexeyNemytov** [comment]
@kolmanv @yarondbb @genadyp 
Content and backup server are running f1 and f2
File utils generating files (run from f1)
Files are being copied
basically test is running 24/7 now

---

Couple of "Big Buts":
1.  Testing server is not working
2.  bg_command not working (so running from tmux)
3.  Not enough space in f2  - when copied 28Mb - it says disk quota exceeded 

---

Please monitor bbfsdev@gmail.com for errors
Have a great Holiday!

**Comment by kolmanv** [comment]
Please check how much space is available in f2. Please contact Shiray and Kostya about this. Ask them to allocate few GB for testings.
Other issues are commented #135 and  #133

**Comment by AlexeyNemytov** [comment]
@kolmanv @genadyp @yarondbb @vshiray 
Content and backup are running from tmux
File generation is on - to generate files every hour
Files being copied (meantime :)) )

**Comment by bbfsdev** [comment]
Great work. Unassigning for now. When testing_server will be fixed, need to run testing server as needed.

**Comment by bbfsdev** [comment]
Blocked by #135
