### ISSUE TITLE
Faster releases with smaller changes.

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#131]
How to make us release twice a week?
1) Automation:
- [ ] Push button Master/Bakcup servers.
- [ ] Push button Testing server.
- [ ] Wizard for configuration files.

2) Isolation, i.e., easy to run many Testing/Master/Backup setups.
- [ ] Files
- [ ] Ports
- [ ] Easy to manage different runs.

3) Management
- [ ] Divide tasks to small less dependent chunks.

Consider generating a milestone instead of this issue.

**Comment by kolmanv** [comment]
@yarondbb @genadyp @AlexeyNemytov @vshiray 
What do you think? Worth the effort? Is this needed?

**Comment by AlexeyNemytov** [comment]
Definitely yes

**Comment by bbfsdev** [comment]
Obsolete closing.
