### ISSUE TITLE
Bad configuration files examples

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#132]
content_server --conf_file=/home/alexeyn/.bbfs/etc/config_content_server.yml --bg_command=start

[ERROR] [2013-05-11 10:31:05] [content_server:28:Exception happened in content_server server: RuntimeError:before using parameter:'log_param_max_elapsed_time_in_seconds_from_last_flush', it should first be defined through Param module methods:Params.string, Params.path, Params.integer, Params.float or Params.boolean.]
Backtrace:
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/params-1.0.0/lib/params.rb:154:in `raise_error_if_param_does_not_exist'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/params-1.0.0/lib/params.rb:169:in`[]'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/run_in_background-1.0.0/lib/run_in_background.rb:221:in `start!'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/run_in_background-1.0.0/lib/run_in_background.rb:409:in`run'
/usr/local/rvm/gems/ruby-1.9.2-p320/gems/content_server-1.0.0/bin/content_server:20:in `<top (required)>'
/usr/local/rvm/gems/ruby-1.9.2-p320/bin/content_server:19:in`load'
/usr/local/rvm/gems/ruby-1.9.2-p320/bin/content_server:19:in `<main>'
/usr/local/rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in`eval'
/usr/local/rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in `<main>']

**Comment by kolmanv** [comment]
The configuration file is old, i.e., before we moved to log4r. This flag does not exists any more.
The configuration files should be updated. Just delete this flag.

**Comment by kolmanv** [comment]
@AlexeyNemytov Can you handle this?

**Comment by kolmanv** [comment]
There are probably more "bad" flags.
Use configuration examples from our [release notes](https://docs.google.com/document/d/1qFMYTv-iZFA1sZOBLxBjCbSPIHwtCuITl_8u_QW936I/edit)

**Comment by bbfsdev** [comment]
@AlexeyNemytov Any progress?

**Comment by bbfsdev** [comment]
Not relevant any more, the parameters under examples are updated. Closing issue.
