### ISSUE TITLE
Run in background fail

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#133]
Run in background command is not avvailble for this release

**Comment by genadyp** [comment]
@AlexeyNemytov 
Could you add more details?
- Exact run command
- Error Backtrace

**Comment by AlexeyNemytov** [comment]
bg_command=start
please run it with latest release

**Comment by bbfsdev** [comment]
Gena, please check this issue. What seems to be the problem. Assigning to you as we talked today morning.

**Comment by genadyp** [comment]
@AlexeyNemytov 
Could you give an additional data, please?
What is a branch?
What is a config file?
Thank you :)

**Comment by AlexeyNemytov** [comment]
@genadyp  please do the following
1. Install release using [1.0.0 release notes](https://docs.google.com/document/d/1qFMYTv-iZFA1sZOBLxBjCbSPIHwtCuITl_8u_QW936I/edit)..
2. Run:  content_server --conf_file=path_to_configuration_file --bg_coomand = start

**Comment by genadyp** [comment]
New log wasn't treated properly
Fix branch: issue133

> f2 bbfs]$ ruby -Ilib bin/backup_server --conf_file=~/.bbfs/etc/config_backup_server.yml --bg_command=start
> daemon/service backup_server started
> f2 bbfs]$ ps -fu $USER
> UID        PID  PPID  C STIME TTY          TIME CMD
> genadyp  20975 20973  0 09:45 ?        00:00:02 sshd: genadyp@pts/2
> genadyp  20976 20975  0 09:45 pts/2    00:00:00 -bash
> genadyp  24890     1  2 10:49 ?        00:00:0 backup_server  
> genadyp  24911 20976  0 10:49 pts/2    00:00:00 ps -fu genadyp

# 

> f1 bbfs]$ ruby -Ilib bin/content_server --conf_file=~/.bbfs/etc/config_content_server.yml --bg_command=start
> daemon/service content_server started
> [genadyp@f1 bbfs]$ ps -fu $USER
> UID        PID  PPID  C STIME TTY          TIME CMD
> genadyp   7316     1  0 Dec05 ?        00:02:55 tmux new
> genadyp   7318  7316  0 Dec05 pts/31   00:00:00 -bash
> genadyp   7327  7325  0 Dec16 ?        00:00:00 sshd: genadyp@pts/10
> genadyp   7328  7327  0 Dec16 pts/10   00:00:00 -bash
> genadyp   7472  7470  0 Dec16 ?        00:00:00 sshd: genadyp@pts/44
> genadyp   7473  7472  0 Dec16 pts/44   00:00:00 -bash
> genadyp   7551  7549  0 Dec16 ?        00:00:01 sshd: genadyp@pts/46
> genadyp   7552  7551  0 Dec16 pts/46   00:00:00 -bash
> genadyp   7933  7552  0 Dec16 pts/46   00:00:01 ssh f2
> genadyp  11450  7316  0 Dec05 pts/32   00:00:00 -bash
> genadyp  12736     1  0 Dec16 ?        00:00:00 content_server  
> genadyp  12752  7328  0 Dec16 pts/10   00:00:00 ps -fu genadyp

File were copied successfully from master to backup

**Comment by genadyp** [comment]
@kolmanv 
What branch this fix should be merged?

**Comment by bbfsdev** [comment]
Probably master as this does not go to patch 1.0.1

**Comment by genadyp** [comment]
@bbfsdev 
review and merge it into master please

**Comment by bbfsdev** [comment]
Reviewed, please merge.
Maybe publish the gem? What do you think?
Should we do release for that?
@yarondbb @AlexeyNemytov What do you think?

**Comment by bbfsdev** [comment]
Gena, code reviewed, please merge and close issue.

**Comment by genadyp** [comment]
Issue133 branch merged into master
