### ISSUE TITLE
Testing Server Gem

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#134]
Build Gem for testing server

**Comment by AlexeyNemytov** [comment]
gem build testing_server.gemspec
Invalid gemspec in [testing_server.gemspec]: uninitialized constant Gem::Specification::FileCopy
ERROR:  Error loading gemspec. Aborting.

**Comment by kolmanv** [comment]
Change FileCopy:: with TesingServer (see here: https://github.com/bbfsdev/bbfs/blob/master/lib/testing_server/version.rb)

**Comment by bbfsdev** [comment]
@AlexeyNemytov What is the status? Did you build? Please close issue when done.

**Comment by bbfsdev** [comment]
Obsolete.
