### ISSUE TITLE
Need Quota for f2

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#137]
Required quota for f2:
 -bash-4.1$ df
Filesystem           1K-blocks      Used   Available    Use% Mounted on
/dev/simfs            31457280  31448096      9184     100% /
none                   1048576         4            1048572   1% /dev

**Comment by kolmanv** [comment]
[root@f2 log]# ls -l /home/kolmanv/.bbfs/log/
total 23882072
-rw-rw-r-- 1 kolmanv kolmanv    12253909 Apr 10 04:55 backup_file_monitoring.log
-rw-rw-r-- 1 kolmanv kolmanv 24441790464 Apr 10 04:56 backup_server.log
-rw-rw-r-- 1 kolmanv kolmanv     1175552 Apr 10 05:13 testing_server.log.log4r

@AlexeyNemytov I have freed 2GB of space. Please check and close this issue.

**Comment by AlexeyNemytov** [comment]
Closed Thanks
