### ISSUE TITLE
Parameters - default configuration files or simple init to generate .bbfs directory + config files.

### ISSUE THREAD

**Issue by bbfsdev** [bbfsdev/bbfs#141]
All parameters can be put in configuration files.
Every program have a default configuration file which can be changed with command line parameters.

Example:
I was unable to start "backup_server" without "--conf_file".

**Comment by bbfsdev** [comment]
I have talked to Shiray, the only thing he wants is that is we put the config file user ~/.bbfs/etc/content_server.yml
Then by default the program will try to read this specific file.

Gena, please talk to me...

**Comment by genadyp** [comment]
@kolmanv 
@yarondbb 
@vshiray 

as a temp solution defaults were added:
ContentServer: ~/.bbfs/etc/config_content_server.yml
BackupServer: ~/.bbfs/etc/config_backup_server.yml

Need to note it in release notes

---

Servers failed to start with defaults.
Need to determine what are the parameters that must be set manually.

**Comment by bbfsdev** [comment]
Updated [release notes](https://docs.google.com/document/d/1-jEYl9VimfOER7uulxufHvILN4pOkCtCEPXYXvpsbKA/edit#).

**Comment by bbfsdev** [comment]
Not blocking release any more, unassigning and removing milestone.

**Comment by bbfsdev** [comment]
Done.
