### ISSUE TITLE
Enable log rotation.

### ISSUE THREAD

**Issue by bbfsdev** [bbfsdev/bbfs#144]
Compress, store and archive log, continue with empty file.

[Pointer for reading](http://snipplr.com/view/26962/)

**Comment by yarondbb** [comment]
@kolmanv , I ahve assigned it to me as we agreed.

**Comment by bbfsdev** [comment]
Not high priority, unassigning.

**Comment by yarondbb** [comment]
done. Default rotation size is 1M. When file reaches thi size it is closed and new file with increased rotation index is used for rest of logging. rotation index is added right before the '.' char. Exacmple: content_server00001.log4r
