### ISSUE TITLE
data_flush_delay is starving the file write of content data

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#146]
A starvation scenario:
1. Monitoring is sending event of a new file starved.txt to index
2. File starved.txt is indexed
3. Parameter data_flush_delay prevents the new starved.txt file to be written to the file
4. No more monitoring events are coming
5. starved.txt content is never copied to a file

Note that the system works OK in a sence that sync is done OK. This is becuase content server sends to backup server the content.data which is in memory and not the file itself.

**Comment by yarondbb** [comment]
The fix can be made in Master since I merged all patch_1_0_1 into master

**Comment by bbfsdev** [comment]
Not in high priority, unassigning for now.

**Comment by yarondbb** [comment]
done on master
