### ISSUE TITLE
Move file_monitoring to log4r

### ISSUE THREAD

**Issue by bbfsdev** [bbfsdev/bbfs#148]
This is not the correct way to log: [link](https://github.com/bbfsdev/bbfs/blob/master/lib/file_monitoring/file_monitoring.rb#L50)

**Comment by yarondbb** [comment]
Monitor log uses general log params: log_flush_each_message and log_rotation_size.
It has also its own param:default_monitoring_log_path
Other then this it is independent of the general logging system.

**Comment by yarondbb** [comment]
it also uses general log param:log_rotation_size
