### ISSUE TITLE
New Testing Server 

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#150]
Run testing server on content server
  Run local content server (on thread)
  Loop:
    Generate files
    Wait (for index to be written to file)
    locally shallow check (index against physical)

Run testing serer on backup server
   Run local backup server (on thread)
   loop: (based on comperator cycles - after compare wait few minutes for files to be transfered)
     locally shallow check
     Copy content data from memory from master to backup (same as today logic)
     compare master content file against backup local file

Notes:
  configuration file of testing server will include all parameters of content_server, backup_server and file_generator   

Running is basic:
 Prepare configuration file for testing server (master) and testing server (backup) - these will not be changed rapidlly.
 Run Testing server on master
 Run Testing server on backup

**Comment by bbfsdev** [comment]
The idea is to run one executable for testing server (one additional thread) + content server and one for testing server (one additional thread) + backup server.

One option is to add flag to content_server and backup_server: --run_testing_thread=true
This will run the testing thread in addition to running the standard content/backup servers.

Other option is the other way, i.e., add two flags to testing server: --run_content_server=true/false and --run_backup_server=true/false

**Comment by vshiray** [comment]
What is an advantage to put the "testing" part in the main application ?

**Comment by yarondbb** [comment]
I agree with Shiray. 
I think the testing aplication should be seperate application which uses the content_server, file_utils,.. gems.

**Comment by genadyp** [comment]
Who should be a user of testing server?
What is a purpose of testing server?
As far as i can see it used for testing basic functionality of application, that nothing was broken during development, may be some statistics, some research data irrelevant for end-user, etc.
Adding testing server functionality, irrelevant for main application, to main application can make main application logic more complicated.

**Comment by yarondbb** [comment]
Gena,
Kolman and me overviewd the details together. Pls talk to me before starting coding to see that we are alligned

**Comment by bbfsdev** [comment]
If I understand what you wrote then we all agree on the following solution:
separate testing_server executable.
Which can run from within: content_server/backup_server/file_generator/validator with some testing logic.

**Comment by bbfsdev** [comment]
The users are us first of all.

**Comment by genadyp** [comment]
@kolmanv 
@yarondbb 
@AlexeyNemytov  

[New Testing Server branch](https://github.com/bbfsdev/bbfs/tree/issue150)

Servers will be run independently on master and backup machines.
How to run on content side:
testing_server --conf_file=[~/.bbfs/etc/content_testing_server.yml](https://github.com/bbfsdev/bbfs/blob/issue150/examples/content_testing_server.yml) --server_to_test=content
How to run on backup side:
testing_server --conf_file=[~/.bbfs/etc/backup_testing_server.yml](https://github.com/bbfsdev/bbfs/blob/issue150/examples/backup_testing_server.yml) --server_to_test=backup

## Algorithm

**BackupServer side:**
- run BackupServer as a thread from TestingServer
- Per validation_interval send to the TestingServer request to get a fresh index
- When message containing index received:
  - All contents that were indexed on master must be backup-ed till (now + time_backup_requirement). Then validating on backup all contents that were indexed upto (-time_backup_requirement)
  - Validate all already backup-ed contents 
- When validation status from master received
  - Store it
- When all validations on master and backup sides are done
  - Send a mail (So mail sent ~ per validation_interval periods of time)

**ContentServer side:**
- run ContentServer as a thread from TestingServer
- run FileGenerator as a thread from TestingServer
- Main loop:
  - When request from backup side received
    - Send to backup side latest index
    - Validate latest index and send to backup side a validation status 

---

Comments are welcome

**Comment by genadyp** [comment]
**TODO**
- Get latest ContentData object directly from Content/BackupServer.
  Then need changes in Content/BackupServers interfaces
- Split to Backup/ContentTestingServers separate classes?
- Split long methods
- Tests
- No default config taken by Params
- Additional testing scenarios (remove/rename/change)
- In thus implementation validation called automatically on master side
  with receiving GET_INDEX message.
  More flexible will be separating it to two separate operations:
  GET_INDEX and VALIDATE
- Add command line help/usage for executable

---

Is there something urgent that should be fixed this iteration?

**Comment by genadyp** [comment]
**NOTE**
FileUtils version advanced, so there is a need to issue new gem
Params version advanced, so there is a need to issue new gem

**Comment by genadyp** [comment]
@bbfsdev 
Review, please
