### ISSUE TITLE
Shiray:  I have lost my backup.data file after terminating a program in a console.

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#152]
It's a memory usage in 5 minutes after starting.
The configuration is set to monitor 3 directories with a total of 36555 files only.

I have lost my backup.data file after terminating a program in a console.

**Comment by yarondbb** [comment]
I think this issue is fixed in master - Now printing the content data each xxx seconds to file regardless if monitoring event happened.

**Comment by yarondbb** [comment]
On terminating catch block we should force write the content data to file

**Comment by bbfsdev** [comment]
Check with @vshiray how critical is this?

**Comment by vshiray** [comment]
It's not so critical.
But rewriting the data file is a bad approach in any case.

**Comment by bbfsdev** [comment]
Same as #152, read there, closing.
