### ISSUE TITLE
Shiray: You must not overwrite existing data file.

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#153]
You must not overwrite existing data file.
You should create a new file and than renaming it.
It's good to store the previous data file also

**Comment by bbfsdev** [comment]
Talk with @vshiray, is this critical?

**Comment by bbfsdev** [comment]
Same as #152. Not critical. Shiray means that we should write content_data to tmp file and only when the file has finished writing we should move it to the correct place. We should not have many instances of content_data.

**Comment by yarondbb** [comment]
Done. Regarding many instances of content data, we have dynamic content data (thread safe) and another object used by indexer

We need to concider this duplicity.
