### ISSUE TITLE
Concider combine Monitoring and Indexing

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#154]

**Comment by genadyp** [comment]
it looks that indexer in the form that it was written once isn't in use.
it used now for indexing one file but was projected to index file-system tree.

**Comment by bbfsdev** [comment]
I think better idea is to revise indexer and make it very small. But still leave monitoring and indexing as different services.

**Comment by bbfsdev** [comment]
If I understand correctly we are not going to combine those, but rather revise the indexer. Closing issue.
