### ISSUE TITLE
Enable process variables monitoring from web

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#165]
Enbaled with basic variables:
  {server_name:content_server} , 
  {time:2013-06-09 14:48:18 +0000} , 
  {monitoring queue size:9397} , 
  {content data queue:1} , 
  {indexed_files:4192}

To use it pls add the following parameters in configuration file:
# process variables monitoring

   process_monitoring_web_port: 5556
   enable_monitoring: true
   process_vars_delay: 2

**Comment by yarondbb** [comment]
To use it: type in browser: <server-name>:<port>

We need to think of more valuable parameters for on-line debug the system

**Comment by yarondbb** [comment]
type in browser:   server_name:port_number
for example: localhost:5555

**Comment by bbfsdev** [comment]
Nice work. @vshiray - You can debug the system using this feature.
Shiray, please tell us what internal data would you like to see there to debug MEM consumption?

@yarondbb  - I suggest embedding the profiling tool within our program and displaying memory consumption and data structure on the fly using this feature...

**Comment by yarondbb** [comment]
The memory profiling tool suggested can not be used (some broken link in the tool guide)
The existing new process variable monitoring tool has been enhanced:
1. All queues sizes added
2. Object Construct\Distruct count for: 
   ContentData
   FileStat
   DirStat
   DynamicContentData
1. Total count of living objects (Live objs cnt - variable below)

Look on this sexample of content_server:
{server_name:content_server} , 
{obj add ContentData:302} , # this is the construct variable
{obj add DynamicContentData:1} , 
{obj add DirStat:2} , 
{obj add FileStat:259} ,
 {time:2013-06-11 13:09:21 +0000} , 
{File Streamer queue:0} , 
{monitoring queue:0} , 
{content data queue:0} ,
{copy files events queue:0} , 
{Live objs cnt:184350} , 
{obj rem ContentData:299} , # this is the disstruct variable 
{indexed_files:257}

If we see that object count keeps growing we can add the specific object count by class types if necessary to trace the leak..

I suggest to create some eng version (of master) for @vshiray and debug on his system using the new capability

**Comment by yarondbb** [comment]
Commited to branches: 
  patch_1_0_3
  release_1_1_0
