### ISSUE TITLE
Process vars analisys of (Indexing rate ; queue performence ; log size) for 32K files

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#166]
Using new 'process variables monitoring' capability shows:
On Windows, with new designe, branch: release_1_1_0 -  32K files with 200-5K:

Indexing:
Indexing rate starts with 100 files per second (should finish indexing in ~5.5 minutes.
But through time rate drops more and more. Eventually it took 6 hours to complete.

Queue size(files waiting to be indexed) is going up to 23K and starts dropping only when files are finished to be pushed.
But when it drops down the indexing rate is still droping..

Conclusion-dropping indexing rate root cause is unknown

Log: (rotation of 1M is used) - new files are created each 1M byte.
13M size of log (info level) - due to index line per file. We can concider dropping this becuase process varailbes can give us life signals. also they are printed to log every few seconds.
Monitoring log - ~8M
Overall - ~20M which is very big logs..

**Comment by bbfsdev** [comment]
@yarondbb  please do the analysis in Linux.

Please monitor all available queues.
If you can add memory consumption data to monitoring.

**Comment by bbfsdev** [comment]
@yarondbb 
If I understand correctly this issue is solved. Please close it.
