### ISSUE TITLE
Reorginize GEMs

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#177]
Right hand rule: 
If GEM content is related to content server such as: file monitoring, content data, process monitoring ets, then put inside content server gem (is sub dirs)

If GEM content is not related to content server such as: Networking, log, params etc, then keep as seperate gem

**Comment by bbfsdev** [comment]
The new suggest list of gems is:
1) bbfs (rename content_server to bbfs)
  We can keep subdirectories here with same names.
2) networking
3) params
4) run_in_background
5) (maybe) process_monitoring
6) (maybe) log

**Comment by genadyp** [comment]
Suggest to move everything to one gem.
In the current situation there is no need to support a number of gems.
Let's think about it when there is indeed will be a need.

@yarondbb 
@kolmanv 
@AlexeyNemytov 
What are you thinking? Is it OK?

**Comment by genadyp** [comment]
@yarondbb 
@kolmanv 
@AlexeyNemytov 

Software will be supplied as one gem: content_server-X.X.X.gem
Unused gemspecs moved to legacy folder.

To check gem it was installed on content and backup machines and then testing server activity was simulated on two machines.
Was unable to run testing_server even with clean master taken from repository.

**Comment by bbfsdev** [comment]
@genadyp do you plan move all files under the content_server directory, remove old unused files.

**Comment by genadyp** [comment]
Why to move all files under content_server directory?
There are different modules, does not connected directly to content_server logic (right hand rule from the first message of this issue).
Suggest to remain project separation to module as it, just build one gem cause now there is no reason to support number of gems.
There two different systems: module system (logical division of the project, number of modules, according to code cohesion) and gem system (distribution division, suggested to use only one gem).
Old files are in legacy directory, that is out of gem distribution.
This directory just like something as a trash folder.

**Comment by bbfsdev** [comment]
**TODO**
1) I suggest deleting the legacy folder as we have everything stored in git and we can alway go back.
2) In order for the project to remain in the correct gem structure there should be:
lib/<gem name> directory
Then under this directory we can divide and create all modules.
So the basic thing is to move all directories under lib to directory lib/<gem name> such that the correct gem structure will remain. This is the accepted gem structure in the community.
Also suggest to delete files we don't use (should be some, not just gemspects).

**Comment by genadyp** [comment]
**TODO** 
Move [ThreadSafeHash](https://github.com/bbfsdev/bbfs/blob/master/lib/process_monitoring/thread_safe_hash.rb#L2) to another place out of lib/process_monitoring
