### ISSUE TITLE
Windows\Linux paths handling

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#183]
This exception is thrown in Linux when backup destination folder path is provided in Windows format: ~.bbfs\test_backup_dir
     Exception happened in testing_server server: ArgumentError:user .bbfs\test_backup_dir doesn't exist

We might want to handle this and allow any format to be provided (thus having 1 configuration file format for linux Windows)

**Comment by bbfsdev** [comment]
There is an error in your input:

```
~.bbfs\test_backup_dir
```

should be

```
~\.bbfs\test_backup_dir
```

Try changing... If the problem is not recreated, close the issue.
