### ISSUE TITLE
File names encoding

### ISSUE THREAD

**Issue by genadyp** [bbfsdev/bbfs#2]
To check that indexer works with various file names encodings.
If file is not in UTF-8 format then omit it

**Comment by kolmanv** [comment]
Are you planning on adding test for that?

**Comment by genadyp** [comment]
It was already partly done.
I'll finish it after current task.

**Comment by bbfsdev** [comment]
"content_server" failed with messages:

[INFO] [2013-05-26 11:43:34] [queue_indexer.rb:50:Indexing content /mnt/storage/media/audio/25_ogon�k.mp3.]
[ERROR] [2013-05-26 11:43:34] [backup_server:31:Exception happened in backup_server server: ArgumentError:invalid byte sequence in UTF-8]

It must log and ignore to process any names which are not UTF-8 compliant.

Here you can find some malformed utf-8 strings:
http://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-test.txt
http://stackoverflow.com/questions/1319022/really-good-bad-utf-8-example-test-data

**Comment by bbfsdev** [comment]
@yarondbb Can you please update the status? Close if needed.
