### ISSUE TITLE
application name changed to ruby_wrapper..

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#215]
Starting version 1.2.1 (ingle gem), the application name has changed to ruby_wrapper..

This obligates the user provide the conf file explicitly (work around)

**Comment by genadyp** [comment]
@yarondbb 
@AlexeyNemytov 
@kolmanv 

When providing executables with a gem, they get wrapped in a ruby wrapper that provides some support for using previous versions of a gem. So ruby_wrapper is OK.

[This line suspicious](https://github.com/bbfsdev/bbfs/blob/master/lib/params.rb#L256):
`Params['conf_file'] = "~/.bbfs/etc/config_#{executable_name}.yml"`

In the previous version, supplied with v1.2.0, we used hardcoded values and regular expressions to determine which config to take:

```
if $0 =~ /content_server/
    Params.path('conf_file', '~/.bbfs/etc/config_content_server.yml', 'Configuration file path.')
  elsif $0 =~ /backup_server/
    Params.path('conf_file', '~/.bbfs/etc/config_backup_server.yml', 'Configuration file path.')
  elsif $0 =~ /testing_server/
    Params.path('conf_file', '~/.bbfs/etc/testing_server.yml', 'Configuration file path')
  else
    Params.path('conf_file', nil, 'Configuration file path.')
  end
```

 Suggested to return to previous version.

Alternatively we can use regular expressions:

ruby_noexec_wrapper code:

```
#!/usr/bin/env ruby

original_file=ARGV[0]
ARGV.shift
$PROGRAM_NAME=original_file

require 'rubygems'
begin
  require 'rubygems-bundler/noexec'
rescue LoadError
  warn "unable to load rubygems-bundler/noexec" if ENV.key?('NOEXEC_DEBUG')
end

eval File.read(original_file), binding, original_file
```

Then original executable is a first parameter for ruby_noexec_wrapper script.
For example:
ruby_noexec_wrapper content_server

Also looks like _$PROGRAM_NAME_ global variable contains original name.
This is may be the best solution that worth to check.

**Comment by genadyp** [comment]
issue215_ruby_noexec_wrapper_fix
branch created

**Comment by genadyp** [comment]
Validation:

```
[genadyp@lnx-genadyp bbfs]$ rm ~/.bbfs/log/*
[genadyp@lnx-genadyp bbfs]$ ruby -Ilib bin/content_server 
^C
Interrupt or Exit happened in server:'content_server'.
Exception type:'Interrupt'.
Exception message:''.
Stopping process.
Force writing local content data to /home/genadyp/.bbfs/var/content.data.

[genadyp@lnx-genadyp bbfs]$ grep conf_file /home/genadyp/.bbfs/log/content_server000001.log
[INFO] [2013-08-19 18:40:54] [log.rb:116:Param #1: conf_file=/home/genadyp/.bbfs/etc/config_content_server.yml]

[genadyp@lnx-genadyp bbfs]$ 
[genadyp@lnx-genadyp bbfs]$ cd
[genadyp@lnx-genadyp ~]$ rm ~/.bbfs/log/*
[genadyp@lnx-genadyp ~]$ backup_server 
Interrupt or Exit happened in server:'backup_server'.
Exception type:'Interrupt'.
Exception message:''.
Stopping process.

[genadyp@lnx-genadyp ~]$ grep conf_file /home/genadyp/.bbfs/log/backup_server000001.log4r 
[INFO] [2013-08-19 18:41:42] [log.rb:116:Param #1: conf_file=/home/genadyp/.bbfs/etc/config_backup_server.yml]
```

**Comment by yarondbb** [comment]
Merged
