### ISSUE TITLE
Monitoring - new use case

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#237]
Use case:
Folder was renamed, then no need to re-index (no files were added/changed) inner files - only to update ContentData.

In general if there is a file with same file attributes as in ContentData, then no need to re-calculate checksum for this file, just to update ContentData.

Remarks?

**Comment by yarondbb** [comment]
phases:
0. Application runs in 'normal' state.
1. User sends 'hold' signal
2. The system moves to 'hold' state and indicates this to user
3. User perform changes in diretories structure (rename directories, delete\add files)
4. User sends 'resum' sugnal
5. System move to 'resum' state. in which:
5.1   Monitoring the file system.
5.2      If Files added\delete - behave as normal state i.e. add\delete from content data
5.3      if Files already exist (same name,size, and mod time) in other dir, then use the existing checksum. Update (overrite) the content data new path of the file.
5.4      When writing to file, the new updated content data will be written.
5.5  Move to 'normal' state and indicate the user that changes were updated in Application and in content.data file.

**Comment by yarondbb** [comment]
```
Use case:
```

Folder was renamed, then no need to re-index (no files were added/changed) inner files - only to update    ContentData.

Shiray: It's an example only which can bring a huge data reindexing.
It maybe any other small changes also (move files to another folders, delete some files, ...).

```
In general if there is a file with same file attributes as in ContentData, then no need to re-calculate checksum for  this file, just to update ContentData.
```

Shiray: It's not a regular behavior now.
We do checksumming in case we see a new file.
But probably we can add an optional parameter per indexing directory in the configuration file.
So we can get this behavior as default.

**Comment by yarondbb** [comment]
If we are going to add this behavior thorugh new parameter per dir, then we would not need the signals flow any right ?

To check if file attributes already exist, we would search the directory tree and look for a match.
     Time performence is:
     O(log-n) +                  O(1) =                                   0(log-n)
      Dir Tree search        Files hash under dir
     This is not too heavy. 
      Maybe we can use this search as a default behavior.

We can run a test to see the differences in Time

**Comment by bbfsdev** [comment]
What do you mean new parameter per dir?
I suggest instead of parameters going for simpler design.
If Shiray want such behavior, he stops the server (in clean predefined way), and rerun with special flag, i.e., allow_move_for_first_index=true, then in the first index run we may allow this "move" check and not reindex moved files.
Or we could simply implement hold/resume button. We can do this through HTML UI (we use Sinatra) or with Linux signals.

**Comment by yarondbb** [comment]
Agreed solution:

User flow:
1. Stop the application
2. Run Do manual changes in monitoring directories (any change)
3. Run the application with new flag: manual_file_change=true
4. Application should provide new content data file with the manual changes (without doing any indexing), and exit
5. Run application again with new flag: manual_file_change=false (default calue). Application will load the uchanged content data file and continue

Alogorithm for step 3:
  load content data with new flag: 'manual_file_change'
  During load the application will builld new map: 
    file,size,mod --> [checksum, uniqu]
  If key found more then 1 time,then uniqu become false. This will indicate not to do anything with it during manual change

  monitoring new behavior: 
    existing files in Application Tree - ignore
    new found files in OS system:
      If not exist in map - need to be indexed. skip (will be handled in step 5.
      If exist in map (copied or moved): 
        if uniqu is true - take the original checksum and add to ContentData
        if uniqu is false - need to be indexed. skip. will be handled in step 5.
    unmarked files (non existing) - will have legacy behavior and be remove from content data
  Write new content data to file
  Exit the application

**Comment by yarondbb** [comment]
issue #242 is the pull request for this issue

**Comment by yarondbb** [comment]
Closing to prevent duplication, since there is a pull request issue opened for this same issue
