### ISSUE TITLE
Log4r new version 11 breaking Master

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#241]
Log4r new version 11 is not compatible with version 10. This breaks Mater.
Workaround is to uninstall ver 11 and install version 10 (or have ver 10 be intalled via bundle install)
Long run is to allign code with new ver 11

**Comment by AlexeyNemytov** [comment]
Working with ruby 1.9.2 
Current valid version of log4r gem is 1.1.10
version 1.1.11 does not exist 
rake with version 1.1.10 is OK 
Could not recreate a problem on my machine 
1. Uninstalled all
2. Installed all
3. rake is OK
4. gem uninstall log4r
5. Check no valid version of log4r exist
6. gem install log4r
7. run rake is OK - 0 errors 0 failures
I checked on ruby site https://rubygems.org/gems/log4r
The latest valid version is 1.1.10
@yarondbb 
@kolmanv 
@genadyp

**Comment by yarondbb** [comment]
I checked the web, it seems that Log4r ver 11 was Yanked due to errors all around teh globe :)
Less work for us..
