### ISSUE TITLE
Convert current content data file format(5 fields) to new format (6 fields)

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#244]
Next release should support new Content data format (new field - instance index time)
Currently the customer has content data file in Current format (5 fields)
Example of content data file name: backup.data-20130801.bz2

New auxiliary conversion application should convert all instances in the input content data file and add an index time for all instances.
The index time will be calculated as follows:
  Read the content data file name with format: 
   <prefix_name>-<year in 4 digits><month in 2 digits><day in 2 digits>.<postfix_name>
Unix-Time (Seconds from Unix epoch) will use the date: <year in 4 digits><month in 2 digits><day in 2 digits>

Summary: convert all instances like this example:
   a1234567890123456789_80124_server1_/user/path_to_file_1389167919
      Will be onverted to:
    a1234567890123456789,80124,server1,/user/path_to_file,1389167919,<Unix-Time >

unix time will be the seconds conversion of the date provided in the file name

**Comment by bbfsdev** [comment]
I don't understand what you mean here... do you talk here about what is the default index time of a file?

We should write a simple file_utils command that converts the content_data to new format.

**Comment by yarondbb** [comment]
Since it is temporary only I think easiest for Customer is to have it as a script under bin.
We will remove it in next release.
