### ISSUE TITLE
Get a diff between old and new content data files

### ISSUE THREAD

**Issue by yarondbb** [bbfsdev/bbfs#246]
Should be done offline on 2 files.
Generate reports, which contents Added, Removed from old to new

**Comment by bbfsdev** [comment]
Please look [file_utils.rb L179](https://github.com/bbfsdev/bbfs/blob/master/lib/file_utils/file_utils.rb#L179), you can see there are 3 actions available for content data (merge, intersect and minus) those are enough to generate the diff.
merge - combine two CD (symmetric)
intersect - return only instances/contents that are in both CD (symmetric)
minus - returns contents/instances that are in A and not in B (asymmetric)

**Comment by genadyp** [comment]
@yarondbb 
@AlexeyNemytov 
@kolmanv 
@vshiray 
Few questions, cause usage is unclear:
- Only diff of contents should be reported?
- What should be a report format - what is an information that user wants to retrieve?
  Say, if we have only content data in the report (checksum, time) - what user can to do with this data?

**Comment by kolmanv** [comment]
First I think the output should be a file in the same format.
It probably should be asymmetric, i.e., give me all instances of contents
which are in content a and are not in content b.
You should output something like:

bbfs> diff cd_a cd_b > cd_diff
There are 512 (569) in cd_b 768 (1012) which are not in cd_a 1096554
(1256778).
Where X (Y) - X is contents and Y is instances.

cd_diff should have the same structure as cd_a

**Comment by genadyp** [comment]
So diff report actually is in the same format as ContentData?
Then it is very close to what we have in [file_utils.rb L179](https://github.com/bbfsdev/bbfs/blob/master/lib/file_utils/file_utils.rb#L179).
We can add few commented lines in the header of the report with an information similar to the command line diff or version control diff (what files were compared, etc).

**Comment by bbfsdev** [comment]
Yes. That what I understand.

**Comment by genadyp** [comment]
Actually we can stay with a file_utils code while:
- we add file_utils to the [gemspec](https://github.com/bbfsdev/bbfs/blob/master/content_server.gemspec#L45), then it will be installed in a system along with other executables
- return a `ContentData.to_s`. i.e. to add `output.to_s` in [file_utils.rb#L100](https://github.com/bbfsdev/bbfs/blob/master/lib/file_utils/file_utils.rb#L100)

Usage for this specific case: 
file_utils --command=minus --cd_a=master.cd --cd_b=remote.cd --dest=absents.cd

@yarondbb 
@kolmanv 
@AlexeyNemytov 
What do you think?

**Comment by yarondbb** [comment]
Yes, this is what shiray wants in general. He does not care the format 
HE wants to provide path to old CD file and path new new CD file and get:
  new contents and their instances in new CD
