### ISSUE TITLE
crawler testing

### ISSUE THREAD

**Issue by genadyp** [bbfsdev/bbfs#4]
Add crawler unit test.
Can be rather difficult cause of SSH connection.

Useful link:
Module Net::SSH::Test
http://net-ssh.github.com/net-ssh/classes/Net/SSH/Test.html

**Comment by vladrbb** [comment]
Gen Spasibo.

-----Original Message-----
From: genadyp [mailto:reply@reply.github.com] 
Sent: Tuesday, July 19, 2011 3:21 PM
To: Vladimir Rogachevsky
Subject: [bbfs] crawler testing (#4)

Add crawler unit test.
Can be rather difficult cause of SSH connection.

Useful link:
Module Net::SSH::Test
http://net-ssh.github.com/net-ssh/classes/Net/SSH/Test.html

## 

Reply to this email directly or view it on GitHub:
https://github.com/kolmanv/bbfs/issues/4

**Comment by genadyp** [comment]
arvut ;))

**Comment by kolmanv** [comment]
Not relevant.
