### ISSUE TITLE
Code styling and code review

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#43]
Yaron hello,

1) Please check why people are not receiving emails when you comment on their code.
2) Please work with Grisha on every pull request you get.
3) Please update our style-guide. Remove all redundant rules, update the link to the style-guide which Rame send us.

**Comment by kolmanv** [comment]
Link to style-guide: https://github.com/bbatsov/ruby-style-guide

**Comment by yarondbb** [comment]
Done.
