### ISSUE TITLE
Code styling tool.

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#46]
Please look for a code styling/lint tool for our project.
This tool should 
We should run it automatically before each commit.
We can do this using pre-commit hook.
For help on this read the following file in a repository: bbfs/.git/hooks/pre-commit.sample

**Comment by gshilin** [comment]
My dear friend, RubyMine is ready for you to do it in a single click.
Just don't be lazy.
:)

On Tue, Jun 12, 2012 at 7:53 AM, kolmanv <
reply@reply.github.com

**Comment by kolmanv** [comment]
We are lazy :) if several hour effort of making automatic check is possible then we should do this.

**Comment by kolmanv** [comment]
Lets use RubyMine for now as Grisha suggests.
