### ISSUE TITLE
Always running backup staging/testing system

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#47]
Gena will tell you how to run processes in background.
Slava will tell you how to generate files for the testing system.

We need to think how to 'update' the staging/testing system code.
Maybe we will create a branch which is called staging. Yaron will merge files there and only after you tested the latest version we will merge this to master.

**Comment by genadyp** [comment]
If needed I can assist.

**Comment by vshiray** [comment]
Please start from the manual testing only.
There is no sense to make things so complex from beginning.

**Comment by kolmanv** [comment]
Alexey, please use Gena to help you out.
Gena you will have other tasks.

**Comment by kolmanv** [comment]
Done.
