### ISSUE TITLE
0MQ

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#48]
1) Learn 0MQ.
2) Design 0MQ usage for our system.
3) Prepare short presentation for everyone.

**Comment by vshiray** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
    Давай это я возьму на себя.
      На это надо много времени, а у меня к тому же уже есть начальная
      база.
      После этого, уже кто то сможет начать этим пользоваться реально.
      On 6/12/2012 8:25 AM, kolmanv wrote:

```
  1) Learn 0MQ.
```

2) Design 0MQ usage for our system.
3) Prepare short presentation for everyone.
4) Implement all changes, replace all netwok communications with 0MQ

---

Reply to this email directly or view it on GitHub:
https://github.com/kolmanv/bbfs/issues/48

**Comment by kolmanv** [comment]
Shiray, please check security too. We need one channel to be secured. Alternative is to encrypt content.

**Comment by kolmanv** [comment]
Volodia any news?

**Comment by kolmanv** [comment]
Obsolete.
