### ISSUE TITLE
Failures running rake on Linux server

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#56]
Failures:

  1) FileCopy::ssh_connect should raise error when username not specified
     Failure/Error: expect { FileCopy::ssh_connect(nil, nil, 'a server') }.should raise_error "Undefined username"
       expected Exception with "Undefined username", got #<NameError: uninitialized constant BBFS::FileCopy::Log>
     # ./test/file_copy/copy_spec.rb:12:in `block (2 levels) in module:Spec'

  2) FileCopy::ssh_connect should try to connect if username is set explicitly
     Failure/Error: FileCopy::ssh_connect('kuku', nil, 'a server')
     NameError:
       uninitialized constant BBFS::FileCopy::Log
     # ./lib/file_copy/copy.rb:14:in `ssh_connect'
     # ./test/file_copy/copy_spec.rb:21:in`block (2 levels) in module:Spec'

  3) FileCopy::ssh_connect should try to connect if username is set via ENV variable
     Failure/Error: FileCopy::ssh_connect(nil, nil, 'a server')
     NameError:
       uninitialized constant BBFS::FileCopy::Log
     # ./lib/file_copy/copy.rb:14:in `ssh_connect'
     # ./test/file_copy/copy_spec.rb:26:in`block (2 levels) in module:Spec'

  4) FileCopy::sftp_copy call upload with correct files
     Failure/Error: FileCopy::sftp_copy(nil, nil, nil, { 'a' => 'b', 'c' => 'd' })
     NameError:
       uninitialized constant BBFS::FileCopy::Log
     # ./lib/file_copy/copy.rb:49:in `sftp_mkdir_recursive'
     # ./lib/file_copy/copy.rb:36:in`block (2 levels) in sftp_copy'
     # ./lib/file_copy/copy.rb:34:in `each'
     # ./lib/file_copy/copy.rb:34:in`map'
     # ./lib/file_copy/copy.rb:34:in `block in sftp_copy'
     # ./lib/file_copy/copy.rb:33:in`sftp_copy'
     # ./test/file_copy/copy_spec.rb:50:in `block (2 levels) in module:Spec'

Finished in 0.00663 seconds
5 examples, 4 failures

Failed examples:

rspec ./test/file_copy/copy_spec.rb:10 # FileCopy::ssh_connect should raise error when username not specified
rspec ./test/file_copy/copy_spec.rb:19 # FileCopy::ssh_connect should try to connect if username is set explicitly
rspec ./test/file_copy/copy_spec.rb:23 # FileCopy::ssh_connect should try to connect if username is set via ENV variable
rspec ./test/file_copy/copy_spec.rb:33 # FileCopy::sftp_copy call upload with correct files
rake aborted!
/usr/local/rvm/rubies/ruby-1.9.2-p320/bin/ruby -S rspec ./test/file_copy/copy_spec.rb ./test/content_server/content_server_spec.rb failed

**Comment by kolmanv** [comment]
Yaron, Hi.

Please notice that the logs break the spec tests (uninitialized constant BBFS::FileCopy::Log). Please fix.

**Comment by kolmanv** [comment]
What is the status of this?

**Comment by yarondbb** [comment]
I have added require 'log' for all files which use the log. This is on master. pls metge master to grab this fix into this branch

**Comment by kolmanv** [comment]
Thanks, you can close the issue.

On Thu, Jul 12, 2012 at 12:18 PM, yarondbb <
reply@reply.github.com
