### ISSUE TITLE
Bug in lib\content_server.rb

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#57]
When executing ruby -Ilib bin/content_server in the master branch on LINUX 
The following error received in line 98 of content_server.rb:
content_server.rb:98:in `block in run': uninitialized constant BBFS::ContentServer::Log (NameError)
1. All parameters initialized according to ReadMe file 
2. The message itself is unclear : What does  it  mean NameError ?

**Comment by yarondbb** [comment]
Need to add a require log to lib/content_serve
I have pushed a fix for Genady and Kolman to review 
the NameError is saying that BBFS::ContentServer::Log is not defined

**Comment by kolmanv** [comment]
will check.

**Comment by kolmanv** [comment]
Fixed.
