### ISSUE TITLE
check while reading parameters from yml file

### ISSUE THREAD

**Issue by genadyp** [bbfsdev/bbfs#59]
params.rb: line15:        if not self.instance_variable_get '@' + param_name
am I right that we check here that parameter was already declared?
if it indeed was declared but its default value is nil
then this check mistakenly returns false
and stop further processing of yml file

**Comment by gshilin** [comment]
That's definitely bad idea to have default value nil.
Nil means "there is no value yet" and hence should be treated as "the variable is known, but not initialized yet".
This way the proper test should be something like: self.instance_variable_get('@' + param_name).nil?

And as I've already told Kolman, it looks like the idea to see parameters as variables causes a very ugly code, both in implementation, and in use.

**Comment by yarondbb** [comment]
Right. All parameters should have default values. This way the type check would also work when using the Command Line parsing code.
I will take care of the Init sequence soon which will read the params from CLI\File\Code

**Comment by kolmanv** [comment]
Not relevant, params system rebuilt.
