### ISSUE TITLE
Rake Failures

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#63]
Hello Friend
Took latest version - this is a result while running rake
If this file not in your responsibility please specify the friend responsible :)
General note : after each merge with master please run rake to ensure all test pass
Thanks

Failures:

  1) FileCopy::ssh_connect should raise error when username not specified
     Failure/Error: expect { FileCopy::ssh_connect(nil, nil, 'a server') }.should raise_error "Undefined username"
       expected Exception with "Undefined username", got #<NoMethodError: undefined method `call' for #<RSpec::Expectations::ExpectationTarget:0x00000000faa910>>
     # ./test/file_copy/copy_spec.rb:12:in `block (2 levels) in module:Spec'

  2) FileCopy::ssh_connect should raise error when server not specified
     Failure/Error: expect { FileCopy::ssh_connect('kuku', nil, nil) }.should raise_error "Undefined server"
       expected Exception with "Undefined server", got #<NoMethodError: undefined method `call' for #<RSpec::Expectations::ExpectationTarget:0x00000000f055a0>>
     # ./test/file_copy/copy_spec.rb:16:in `block (2 levels) in module:Spec'

Finished in 0.01788 seconds
5 examples, 2 failures

Failed examples:

rspec ./test/file_copy/copy_spec.rb:10 # FileCopy::ssh_connect should raise error when username not specified
rspec ./test/file_copy/copy_spec.rb:15 # FileCopy::ssh_connect should raise error when server not specified
rake aborted!
/usr/local/rvm/rubies/ruby-1.9.2-p320/bin/ruby -S rspec ./test/file_copy/copy_spec.rb ./test/content_server/content_server_spec.rb failed

**Comment by bbfsdev** [comment]
Tested this issue in Windowd and Linux. Windows works well, Linux fails. Working to solve.

**Comment by kolmanv** [comment]
Done, send pull request to Yaron (https://github.com/kolmanv/bbfs/pull/64).
Please talk with him to merge fixes faster.

Kolman

**Comment by AlexeyNemytov** [comment]
issue checked on f2 server and closed
Thanks for fast response

**Comment by kolmanv** [comment]
How did you check?
Note that the code is not merged yet to master, talk with Yaron.

On Tue, Jul 10, 2012 at 6:05 PM, AlexeyNemytov <
reply@reply.github.com

**Comment by AlexeyNemytov** [comment]
very simple i executed
git pull https://github.com/kolmanv/bbfs fix_ssh_tests
than run rake on both f1 and f2 =0 zero failures

**Comment by kolmanv** [comment]
cool.

On Tue, Jul 10, 2012 at 7:34 PM, AlexeyNemytov <
reply@reply.github.com
