### ISSUE TITLE
run_in_background_test failure

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#67]
I am not sure there is a bug cause did not succeed to repeat the problem - but check it anyway:)
While taking latest version git pull https://github.com/kolmanv/bbfs master
And then running rake command - the result is:

  1) Failure:
test_functionality(BBFS::TestRunInBackground) [/root/bbfs/test/run_in_background/run_in_background_test.rb:37]:
Exception raised:
<#<RuntimeError: daemon/service good_daemon_test wasn't started in timely manner>>.

20 tests, 190 assertions, 1 failures, 0 errors, 0 skips

**Comment by genadyp** [comment]
What is operating system?

**Comment by AlexeyNemytov** [comment]
Linux

On Wed, Jul 18, 2012 at 10:20 PM, genadyp <
reply@reply.github.com

**Comment by genadyp** [comment]
check, please, that daemons library installed.
it should be installed automatically with "bundle install" command

pid directory (~/.bbfs/pids) should be empty

if it still fails, replace, please, lib/run_in_background.rb with the file from apply_background branch.
this version will issue a log file: ~/.bbfs/log/run_in_background_test.rb.log
add somewhere after 'log' require: Params['log_debug_level'] = 1
and run the test

**Comment by genadyp** [comment]
Do you still encounter this problem?
If now let's close it meanwhile.

**Comment by AlexeyNemytov** [comment]
Issue was not observed anymore

**Comment by kolmanv** [comment]
Please close it.
