### ISSUE TITLE
Params Failures during test execution

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#68]
1. Latest master version check git pull https://github.com/kolmanv/bbfs master 
2. Run rake 

Failures:

  1) Params::parameter should raise an error when trying to define twice the same parameter
     Failure/Error: expect { Params.string 'only_once', '2nd' ,'' }.should raise_error \
       expected Exception with "Parameter:'only_once', can only be defined oncet.", got #<NoMethodError: undefined method `call' for #<RSpec::Expectations::ExpectationTarget:0x00000001fbe7e8>>
     # ./test/params/params_spec.rb:33:in `block (2 levels) in module:Spec'

  2) Params::read_yml_params should raise error when yml parameter is not defined
     Failure/Error: expect { Params::read_yml_params StringIO.new 'not_defined: 10' }.should raise_error \
       expected Exception with "Parameter:'not_defined' has not been defined and can not be overridden. It should first be defined through Param module methods:Params.string, Params.integer, Params.float or Params.boolean.", got #<NoMethodError: undefined method `call' for #<RSpec::Expectations::ExpectationTarget:0x00000001faace8>>
     # ./test/params/params_spec.rb:40:in `block (2 levels) in module:Spec'

  3) Params::read_yml_params Will test yml parameter loading
     Failure/Error: expect { Params::read_yml_params StringIO.new 'tmp4str: strr' }.should_not raise_error
       expected no Exception, got #<NoMethodError: undefined method `call' for #<RSpec::Expectations::ExpectationTarget:0x00000001fa02e8>>
     # ./test/params/params_spec.rb:49:in `block (2 levels) in module:Spec'

  4) Params.parse_command_line_arguments should parse parameter from command line.
     Failure/Error: expect { Params.parse_command_line_arguments ['--tmp6str=9'] }.should_not raise_error
       expected no Exception, got #<NoMethodError: undefined method `call' for #<RSpec::Expectations::ExpectationTarget:0x00000001f92378>>
     # ./test/params/params_spec.rb:141:in `block (2 levels) in module:Spec'

  5) Params.init should override command line arguments correctly.
     Failure/Error: expect { Params.init ['--tmp6str2=9'] }.should_not raise_error
       expected no Exception, got #<NoMethodError: undefined method `call' for #<RSpec::Expectations::ExpectationTarget:0x00000001f8cb80>>
     # ./test/params/params_spec.rb:187:in `block (2 levels) in module:Spec'

Finished in 0.20628 seconds
25 examples, 5 failures

Failed examples:

rspec ./test/params/params_spec.rb:31 # Params::parameter should raise an error when trying to define twice the same parameter
rspec ./test/params/params_spec.rb:39 # Params::read_yml_params should raise error when yml parameter is not defined
rspec ./test/params/params_spec.rb:46 # Params::read_yml_params Will test yml parameter loading
rspec ./test/params/params_spec.rb:138 # Params.parse_command_line_arguments should parse parameter from command line.
rspec ./test/params/params_spec.rb:183 # Params.init should override command line arguments correctly.
rake aborted!
/usr/local/rvm/rubies/ruby-1.9.2-p320/bin/ruby -S rspec ./test/file_generator/file_generator_spec.rb ./test/file_copy/copy_spec.rb ./test/content_server/content_server_spec.rb ./test/params/params_spec.rb failed

**Comment by kolmanv** [comment]
Fixed (fix_ssh_tests).
