### ISSUE TITLE
No notification for wrong params usage

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#77]
Example for wrong usage
C:\Ruby192\bbfs>ruby -Ilib bin/file_utils generate_files 
No warning - error or notification - program just ends

Example for correct usage
C:\Ruby192\bbfs>ruby -Ilib bin/file_utils --command=generate_files --log_write_t
o_console=true --log_debug_level=3

**Comment by yarondbb** [comment]
Why is it an error usage?

**Comment by kolmanv** [comment]
Because the user expects some behavior (he does not know he has spelling
mistake). So the program, when parameter not defined or wrong syntax is
used should alert, at least print info/warning message. Maybe error and
fail totally (better).
