### ISSUE TITLE
Release port after run

### ISSUE THREAD

**Issue by AlexeyNemytov** [bbfsdev/bbfs#80]
Release port after system crash - port remains in use

/usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/socket.rb:136:in `bind': Address already in use - bind(2) (Errno::EADDRINUSE)

**Comment by yarondbb** [comment]
Root cuase was due to ctrl-z in linux which moved the execution to the background and this is why the port was used.

**Comment by kolmanv** [comment]
Why didn't you close this Issue?
