### ISSUE TITLE
backup_destination_folder in content_server set for backup_server where to copy files received from_content_server

### ISSUE THREAD

**Issue by itzhak** [bbfsdev/bbfs#81]
backup_destination_folder passed as argument to content_server set to backup server where to copy files received from content. And when we try to pass backup_destination_folder argument to backup_server there is no effect on backup server.
But from user point it is not right.
As user We expect that We can set to backup_server where to save files received from content_server.

**Comment by kolmanv** [comment]
Checked this today. No need to set backup_destination_folder in content_server, only at backup server.
