### ISSUE TITLE
Cannot start backup_server

### ISSUE THREAD

**Issue by vshiray** [bbfsdev/bbfs#85]
[vshiray@f2 ~]$ backup_server --remote_server=10.100.5.106

/usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/fileutils.rb:243:in `mkdir': Permission denied - /remote (Errno::EACCES)
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/fileutils.rb:243:in`fu_mkdir'
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/fileutils.rb:217:in `block (2 levels) in mkdir_p'
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/fileutils.rb:215:in`reverse_each'
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/fileutils.rb:215:in `block in mkdir_p'
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/fileutils.rb:201:in`each'
        from /usr/local/rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/fileutils.rb:201:in `mkdir_p'
        from /usr/local/rvm/gems/ruby-1.9.2-p320@testing/gems/content_server-0.0.9/lib/content_server/remote_content.rb:41:in`receive_content'
        from /usr/local/rvm/gems/ruby-1.9.2-p320@testing/gems/networking-0.0.9/lib/networking/tcp.rb:210:in `call'
        from /usr/local/rvm/gems/ruby-1.9.2-p320@testing/gems/networking-0.0.9/lib/networking/tcp.rb:210:in`block (2 levels) in start_reading'
        from /usr/local/rvm/gems/ruby-1.9.2-p320@testing/gems/networking-0.0.9/lib/networking/tcp.rb:195:in `loop'
        from /usr/local/rvm/gems/ruby-1.9.2-p320@testing/gems/networking-0.0.9/lib/networking/tcp.rb:195:in`block in start_reading'

**Comment by kolmanv** [comment]
This is a simple problem.
The backup destination folder is not defined, that is why process tries to write locally it will try to write to area without permissions.
Should add better error handling + alert when mandatory flags are not set.

**Comment by kolmanv** [comment]
Fixed.
