### ISSUE TITLE
Indexer performs differently in different environments and different Ruby versions

### ISSUE THREAD

**Issue by genadyp** [bbfsdev/bbfs#9]
WindowsXP / Ruby 1.8.7
9e409338c0d8e0bbdbf5316cb569a0afcdb321db,5474,large_server_1,hd1,C:/Kab.Tech/bbfs/resources/index_agent_test/lib/libexslt.lib,Sun Nov 01 16:53:22 UTC 2009

RedHat Linux / Ruby 1.9.2
54649fa7e4ee23ace5d1a717a80df8a7516d3263,5474,large_server_1,hd1,/gpfs/haifa-h1/05/genadyp/Work/Kab.Tech/bbfs/resources/index_agent_test/lib/libexslt.lib,2009-11-01 16:53:22 UTC

Look at the checksum and date

**Comment by genadyp** [comment]
## From vshiray:

Формат даты желательно определять в самом приложении.
Вариант "2009-11-01 16:53:22 UTC" предпочтительный.

С контрольной суммой не понтяно. Если файлы действительно одинаковые, то где то есть баг.

В линуксе есть консольная утилита sha1sum, которую можно запустить и сравнить результат.
Для Windows тоже есть подобная программа http://www.nfllab.com/sums/sums.zip

**Comment by genadyp** [comment]
## Linux:

>  sha1sum bbfs/resources/index_agent_test/lib/libexslt.lib
> 54649fa7e4ee23ace5d1a717a80df8a7516d3263  /gpfs/haifa-h1/05/genadyp/Work/Kab.Tech/bbfs/resources/index_agent_test/lib/libexslt.lib

## WindowsXP:

>  sha1sum resources\index_agent_test\lib\libexslt.lib
> \54649fa7e4ee23ace5d1a717a80df8a7516d3263 *resources\index_agent_test\lib\libexslt.lib

**Comment by genadyp** [comment]
## WindowsXP:

Ruby 1.9.2 solves the problem with SHA1

**Comment by kolmanv** [comment]
On Mac 1.8.7 SHA1 is ok.

**Comment by kolmanv** [comment]
We have moved to ruby 1.9.2. This solved the SHA1 issue.
Date time single format already pushed.
