### ISSUE TITLE
Change logging to log4r

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#97]
In log.rb, delete all content and replace the init, info, warning, debug1/2/3, error methods to invoke log4r methods. That way all other places should stay as they are now.

Init:
def create_log4r(server_name)
  $log4r = Log4r::Logger.new 'BBFS log'
  $log4r.trace = true

  formatter = Log4r::PatternFormatter.new(:pattern => "[%l] %d #{self.class} %t :: %m")

  stdout_outputtter = Log4r::Outputter.stdout
  stdout_outputtter.formatter = formatter

  file_outputter = Log4r::FileOutputter.new('file_log', :filename =>  "#{Params['log_file_name']}.log4r")
  file_outputter.formatter = formatter

  email_outputter = Log4r::EmailOutputter.new('email_log',
                                              :server => 'smtp.gmail.com',
                                              :port => 587,
                                              :subject => "Error happened in #{server_name} server run by #{ENV['USER']}.",
                                              :acct => Params['from_email'],
                                              :from => Params['from_email'],
                                              :passwd => Params['from_email_password'],
                                              :to => Params['to_email'],
                                              :immediate_at => 'FATAL,ERROR',
                                              :authtype => :plain,
                                              :tls => true)
  email_outputter.level = Log4r::ERROR
  email_outputter.formatter = formatter

  $log4r.outputters << stdout_outputtter
  $log4r.outputters << file_outputter
  $log4r.outputters << email_outputter
end

**Comment by yarondbb** [comment]
done. Both in release candidate brnach round_clock_testing and in master
