### ISSUE TITLE
Wrap run_backup_server and run_content_server with general exception handling

### ISSUE THREAD

**Issue by kolmanv** [bbfsdev/bbfs#98]
Inside those two functions create a begin/end block with two rescues:
1) Signals (such as ctrl+c) - should stop the process/job.
2) Exceptions, which come from inside, should be logged and send via email (log4r emailoutputter).
3) Example below also sugests retry mechanism, such that if some error happened once, the server will restart several times, then will exit.

def run_backup_server(retries=3)
  begin
  rescue SystemExit, SignalException, Interrupt => exc
    log().error("Interrupt or Exit happened in #{server_name} server: #{exc.class}, stopping process.\nBacktrace:\n#{exc.backtrace.join("\n")}")
    raise
  rescue Exception => exc
    log().error("Exception happened in #{server_name} server: #{exc.class}:#{exc.message}")
    if retries > 0
      log().info("Restarting (retries:#{retries}).\nBacktrace:\n#{exc.backtrace.join("\n")}")
      run_backup_server(retries-1)
    else
      log().info("Exiting...\nBacktrace:\n#{exc.backtrace.join("\n")}")
    end
  end
end

**Comment by kolmanv** [comment]
Retry is not critical, so don't implement it as first step.

**Comment by genadyp** [comment]
commit: https://github.com/kolmanv/bbfs/commit/64f3cbbfd365457f0c09f629fe962a6ae9924622

retries doesn't work as smooth as expected,
thus set to 1.

**Comment by kolmanv** [comment]
ack.

**Comment by genadyp** [comment]
Kolman, could you verify and close it?

**Comment by kolmanv** [comment]
Verified.
